package com.sdnah.Ticket_Management_System_.Backend.Infastructure_Layer;

import javax.sql.DataSource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

/**
 * One-shot startup migration that drops the stale CHECK constraint on
 * {@code notifications.type}.
 *
 * <p>The constraint was originally generated by Hibernate based on the
 * enum values that existed at first cold start. Adding new
 * {@link com.sdnah.Ticket_Management_System_.Backend.Domain_Layer.Notifications.NotificationType}
 * constants (e.g. {@code OWNER_APPOINTMENT_REQUESTED}) breaks insertions
 * against an old database because {@code ddl-auto=update} never alters
 * existing check constraints. The {@code columnDefinition = "varchar(64)"}
 * on the entity prevents Hibernate from regenerating it, but the old one
 * still lives on already-deployed schemas — this runner drops it.
 *
 * <p>Idempotent: {@code DROP CONSTRAINT IF EXISTS} on Postgres and a
 * silent best-effort attempt on H2 (which uses different DDL).
 */
@Component
@Order(0) // run before any data loaders
public class NotificationsConstraintMigration implements CommandLineRunner {

    private static final Logger log = LoggerFactory.getLogger(NotificationsConstraintMigration.class);

    private final DataSource dataSource;

    public NotificationsConstraintMigration(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    @Override
    public void run(String... args) {
        try (var conn = dataSource.getConnection();
             var stmt = conn.createStatement()) {

            // Postgres syntax. H2 will throw if the constraint doesn't
            // exist by that name — caught + ignored below.
            stmt.execute("ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_type_check");
            log.info("NotificationsConstraintMigration: ensured notifications_type_check is dropped");
        } catch (Exception ex) {
            // Don't fail startup — log and move on. Worst case the user
            // hits the original error and we tell them again.
            log.warn("NotificationsConstraintMigration: skipped — {}", ex.getMessage());
        }
    }
}
