spring.application.name=Ticket_Management_System_


# Enable the H2 Console so you can see your data in the browser
spring.h2.console.enabled=true

# Set a fixed database URL (mem = in-memory)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ensures Hibernate creates the tables based on your @Entity classes
spring.jpa.hibernate.ddl-auto=update