package com.sdnah.Ticket_Management_System_.Backend.Domain_Layer.Notifications;

public enum NotificationType {
    GENERIC,
    SYSTEM_ANNOUNCEMENT,
    PRODUCER_MESSAGE,
    PURCHASE_SUCCESS,
    EVENT_CANCELLED,
    EVENT_RESCHEDULED,
    ORDER_EXPIRY_WARNING,
    COMPANY_CLOSED,
    COMPANY_REOPENED,
    ROLE_CHANGED,
    MANAGER_APPOINTED,
    MANAGER_REMOVED,
    OWNER_APPOINTED,
    OWNER_REMOVED,
    PERMISSIONS_CHANGED
}
